# Generated by Django 4.1.3 on 2022-12-08 16:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('salary', models.FloatField()),
                ('description', models.TextField(max_length=400)),
                ('experience', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=200)),
                ('creation_date', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1200)),
                ('answer', models.CharField(max_length=240)),
                ('option2', models.CharField(max_length=240)),
                ('option3', models.CharField(max_length=240)),
                ('option4', models.CharField(max_length=240)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='', max_length=64)),
                ('l_name', models.CharField(default='', max_length=64)),
                ('gender', models.CharField(default='', max_length=6)),
                ('email_id', models.EmailField(default='', max_length=254)),
                ('edu_name', models.CharField(default='', max_length=64)),
                ('edu_year', models.CharField(default='', max_length=4)),
                ('edu_collage_name', models.CharField(default='', max_length=120)),
                ('edu_marks', models.CharField(default='', max_length=9)),
                ('internship', models.CharField(default='', max_length=500)),
                ('project_name', models.CharField(default='', max_length=120)),
                ('project_link', models.CharField(default='', max_length=360)),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='img/2022-12-08')),
                ('resume', models.FileField(default='', upload_to='resume/2022-12-08', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('apply_date', models.CharField(max_length=30)),
                ('hired', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
            ],
        ),
    ]
